// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hapi/release/release.proto

package release

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import chart "k8s.io/helm/pkg/proto/hapi/chart"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Release describes a deployment of a chart, together with the chart
// and the variables used to deploy that chart.
type Release struct {
	// Name is the name of the release
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Info provides information about a release
	Info *Info `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// Chart is the chart that was released.
	Chart *chart.Chart `protobuf:"bytes,3,opt,name=chart,proto3" json:"chart,omitempty"`
	// Config is the set of extra Values added to the chart.
	// These values override the default values inside of the chart.
	Config *chart.Config `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	// Manifest is the string representation of the rendered template.
	Manifest string `protobuf:"bytes,5,opt,name=manifest,proto3" json:"manifest,omitempty"`
	// Hooks are all of the hooks declared for this release.
	Hooks []*Hook `protobuf:"bytes,6,rep,name=hooks,proto3" json:"hooks,omitempty"`
	// Version is an int32 which represents the version of the release.
	Version int32 `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	// Namespace is the kubernetes namespace of the release.
	Namespace            string   `protobuf:"bytes,8,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ThreeWayMergeEnabled bool     `protobuf:"varint,9,opt,name=three_way_merge_enabled,json=threeWayMergeEnabled,proto3" json:"three_way_merge_enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Release) Reset()         { *m = Release{} }
func (m *Release) String() string { return proto.CompactTextString(m) }
func (*Release) ProtoMessage()    {}
func (*Release) Descriptor() ([]byte, []int) {
	return fileDescriptor_release_0e0fdaf97189be13, []int{0}
}
func (m *Release) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Release.Unmarshal(m, b)
}
func (m *Release) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Release.Marshal(b, m, deterministic)
}
func (dst *Release) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Release.Merge(dst, src)
}
func (m *Release) XXX_Size() int {
	return xxx_messageInfo_Release.Size(m)
}
func (m *Release) XXX_DiscardUnknown() {
	xxx_messageInfo_Release.DiscardUnknown(m)
}

var xxx_messageInfo_Release proto.InternalMessageInfo

func (m *Release) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Release) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *Release) GetChart() *chart.Chart {
	if m != nil {
		return m.Chart
	}
	return nil
}

func (m *Release) GetConfig() *chart.Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Release) GetManifest() string {
	if m != nil {
		return m.Manifest
	}
	return ""
}

func (m *Release) GetHooks() []*Hook {
	if m != nil {
		return m.Hooks
	}
	return nil
}

func (m *Release) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Release) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Release) GetThreeWayMergeEnabled() bool {
	if m != nil {
		return m.ThreeWayMergeEnabled
	}
	return false
}

func init() {
	proto.RegisterType((*Release)(nil), "hapi.release.Release")
}

func init() { proto.RegisterFile("hapi/release/release.proto", fileDescriptor_release_0e0fdaf97189be13) }

var fileDescriptor_release_0e0fdaf97189be13 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0x43, 0x5b, 0x0a, 0x8c, 0x5e, 0x9c, 0x18, 0xbb, 0x21, 0x1e, 0x88, 0x07, 0x25, 0x1e,
	0x68, 0xa2, 0xf1, 0x05, 0x34, 0x26, 0x7a, 0xf0, 0xb2, 0x17, 0x13, 0x2f, 0x64, 0x8b, 0x43, 0x21,
	0x2d, 0xbb, 0x64, 0x21, 0x9a, 0x3e, 0xa5, 0xaf, 0x64, 0x76, 0x97, 0x2a, 0xd5, 0xcb, 0xc0, 0xcc,
	0xf7, 0xe7, 0x9f, 0x7f, 0x07, 0xe2, 0x4a, 0xb4, 0xf5, 0x52, 0xd3, 0x96, 0x44, 0x47, 0xfb, 0x6f,
	0xd6, 0x6a, 0xd5, 0x2b, 0x3c, 0x36, 0x2c, 0x1b, 0x66, 0xf1, 0xe2, 0x40, 0x59, 0x29, 0xb5, 0x71,
	0xb2, 0x3f, 0xa0, 0x96, 0xa5, 0x3a, 0x00, 0x45, 0x25, 0x74, 0xbf, 0x2c, 0x94, 0x2c, 0xeb, 0xf5,
	0x00, 0xce, 0xc6, 0xc0, 0x54, 0x37, 0xbf, 0xf8, 0x9a, 0x40, 0xc0, 0x9d, 0x0f, 0x22, 0xcc, 0xa4,
	0x68, 0x88, 0x79, 0x89, 0x97, 0x46, 0xdc, 0xfe, 0xe3, 0x25, 0xcc, 0x8c, 0x3d, 0x9b, 0x24, 0x5e,
	0x7a, 0x74, 0x83, 0xd9, 0x38, 0x5f, 0xf6, 0x2c, 0x4b, 0xc5, 0x2d, 0xc7, 0x2b, 0xf0, 0xad, 0x2d,
	0x9b, 0x5a, 0xe1, 0x89, 0x13, 0xba, 0x4d, 0x0f, 0xa6, 0x72, 0xc7, 0xf1, 0x1a, 0xe6, 0x2e, 0x18,
	0x9b, 0x8d, 0x2d, 0x07, 0xa5, 0x25, 0x7c, 0x50, 0x60, 0x0c, 0x61, 0x23, 0x64, 0x5d, 0x52, 0xd7,
	0x33, 0xdf, 0x86, 0xfa, 0xe9, 0x31, 0x05, 0xdf, 0x1c, 0xa4, 0x63, 0xf3, 0x64, 0xfa, 0x3f, 0xd9,
	0x93, 0x52, 0x1b, 0xee, 0x04, 0xc8, 0x20, 0xf8, 0x20, 0xdd, 0xd5, 0x4a, 0xb2, 0x20, 0xf1, 0x52,
	0x9f, 0xef, 0x5b, 0x3c, 0x87, 0xc8, 0x3c, 0xb2, 0x6b, 0x45, 0x41, 0x2c, 0xb4, 0x0b, 0x7e, 0x07,
	0x78, 0x07, 0x8b, 0xbe, 0xd2, 0x44, 0xf9, 0xa7, 0xd8, 0xe5, 0x0d, 0xe9, 0x35, 0xe5, 0x24, 0xc5,
	0x6a, 0x4b, 0xef, 0x2c, 0x4a, 0xbc, 0x34, 0xe4, 0xa7, 0x16, 0xbf, 0x8a, 0xdd, 0x8b, 0x81, 0x8f,
	0x8e, 0xdd, 0x47, 0x6f, 0xc1, 0x90, 0x62, 0x35, 0xb7, 0x37, 0xbe, 0xfd, 0x0e, 0x00, 0x00, 0xff,
	0xff, 0xbb, 0x79, 0x16, 0x84, 0xf2, 0x01, 0x00, 0x00,
}
